import 'dart:io';
import 'package:fit_tool/fit_tool.dart';

void main() async {
  print('🧪 TESTING FIT_TOOL DEFAULT SCALES');
  print('=' * 60);
  
  // 1. Create a file with manually created SessionMessage
  final builder = FitFileBuilder();
  
  builder.add(FileIdMessage()
    ..type = FileType.activity
    ..manufacturer = 1
    ..product = 1
    ..timeCreated = DateTime.now().millisecondsSinceEpoch ~/ 1000
    ..serialNumber = 123
  );
  
  builder.add(SessionMessage()
    ..totalTimerTime = 1000.0 // Expecting 1000 seconds
    ..totalDistance = 1000.0  // Expecting 1000 meters
  );
  
  final fileBytes = builder.build().toBytes();
  
  // 2. Read it back
  final fitFile = FitFile.fromBytes(fileBytes);
  
  // 3. Inspect Definition
  for (final record in fitFile.records) {
    if (record.message is DefinitionMessage) {
      final def = record.message as DefinitionMessage;
      if (def.globalId == 18) { // Session
        print('🔹 SessionMessage Definition (Generated by fit_tool default):');
        for (final field in def.fieldDefinitions) {
          if (field.id == 7) { // total_timer_time
            print('   - total_timer_time (ID 7): BaseType=${field.baseType}, Size=${field.size}');
          }
           if (field.id == 9) { // total_distance
            print('   - total_distance (ID 9): BaseType=${field.baseType}, Size=${field.size}');
          }
        }
      }
    }
    
    if (record.message is SessionMessage) {
      final msg = record.message as SessionMessage;
      print('🔹 Decoded Data:');
      print('   - totalTimerTime: ${msg.totalTimerTime}');
      print('   - totalDistance: ${msg.totalDistance}');
    }
  }
}
